# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nenjOXOrUgpFbSUoRC-5tsXQrzedFFwv
"""

import joblib
import pandas as pd

model = joblib.load('model.pkl')

# Example input
input_data = pd.DataFrame({
    'experience': [3],
    'attendance_rate': [0.9],
    'department_Finance': [0],
    'department_HR': [1],
    'department_IT': [0]
})

prediction = model.predict(input_data)
print("Predicted Salary:", prediction[0])